require("dotenv").config({ path: "../.env" });
const connectDB = require("../config/db");
const Skill = require("../models/Skill");

connectDB();

const skills = [
  { idd: "html", name: "HTML", category: "frontend" },
  { idd: "css", name: "CSS", category: "frontend" },
  { idd: "javascript", name: "JavaScript", category: "frontend" },
  { idd: "typescript", name: "TypeScript", category: "frontend" },
  { idd: "react", name: "React", category: "frontend" },
  { idd: "nextjs", name: "Next.js", category: "frontend" },
  { idd: "vue", name: "Vue.js", category: "frontend" },
  { idd: "angular", name: "Angular", category: "frontend" },
  { idd: "tailwind", name: "Tailwind CSS", category: "frontend" },
  { idd: "bootstrap", name: "Bootstrap", category: "frontend" },
  { idd: "sass", name: "Sass", category: "frontend" },
  // Frontend
  { idd: "redux", name: "Redux", category: "frontend" },
  { idd: "zustand", name: "Zustand", category: "frontend" },
  { idd: "graphql_client", name: "Apollo Client", category: "frontend" },
  { idd: "vite", name: "Vite", category: "frontend" },
  { idd: "webpack", name: "Webpack", category: "frontend" },
  { idd: "pwa", name: "Progressive Web Apps (PWA)", category: "frontend" },
  { idd: "materialui", name: "Material UI", category: "frontend" },
  { idd: "chakraui", name: "Chakra UI", category: "frontend" },
  { idd: "threejs", name: "Three.js", category: "frontend" },
  { idd: "framer", name: "Framer Motion", category: "frontend" },
  { idd: "redux", name: "Redux", category: "frontend" },
  { idd: "zustand", name: "Zustand", category: "frontend" },
  { idd: "graphql_client", name: "Apollo Client", category: "frontend" },
  { idd: "vite", name: "Vite", category: "frontend" },
  { idd: "webpack", name: "Webpack", category: "frontend" },
  { idd: "pwa", name: "Progressive Web Apps (PWA)", category: "frontend" },
  { idd: "materialui", name: "Material UI", category: "frontend" },
  { idd: "chakraui", name: "Chakra UI", category: "frontend" },
  { idd: "threejs", name: "Three.js", category: "frontend" },
  { idd: "framer", name: "Framer Motion", category: "frontend" },
  { idd: "node", name: "Node.js", category: "backend" },
  { idd: "express", name: "Express.js", category: "backend" },
  { idd: "nestjs", name: "NestJS", category: "backend" },
  { idd: "django", name: "Django", category: "backend" },
  { idd: "flask", name: "Flask", category: "backend" },
  { idd: "springboot", name: "Spring Boot", category: "backend" },
  { idd: "laravel", name: "Laravel", category: "backend" },
  { idd: "graphql", name: "GraphQL", category: "backend" },
  { idd: "restapi", name: "REST API Design", category: "backend" },
  {
    idd: "microservices",
    name: "Microservices Architecture",
    category: "backend",
  },
  {
    idd: "authentication",
    name: "Authentication & Authorization",
    category: "backend",
  },
  { idd: "jwt", name: "JWT", category: "backend" },
  { idd: "oauth", name: "OAuth", category: "backend" },
  { idd: "websocket", name: "WebSockets", category: "backend" },
  { idd: "socketio", name: "Socket.io", category: "backend" },
  { idd: "grpc", name: "gRPC", category: "backend" },
  { idd: "prisma", name: "Prisma ORM", category: "backend" },
  { idd: "mongodb", name: "MongoDB", category: "database" },
  { idd: "mysql", name: "MySQL", category: "database" },
  { idd: "postgresql", name: "PostgreSQL", category: "database" },
  { idd: "sqlite", name: "SQLite", category: "database" },
  { idd: "redis", name: "Redis", category: "database" },
  { idd: "dynamodb", name: "DynamoDB", category: "database" },
  { idd: "cassandra", name: "Cassandra", category: "database" },
  { idd: "oracle", name: "Oracle DB", category: "database" },
  { idd: "mariadb", name: "MariaDB", category: "database" },
  { idd: "supabase", name: "Supabase", category: "database" },
  { idd: "firebase_db", name: "Firebase Realtime DB", category: "database" },
  { idd: "elasticsearch", name: "Elasticsearch", category: "database" },
  { idd: "mongodb_atlas", name: "MongoDB Atlas", category: "database" },
  { idd: "python", name: "Python", category: "language" },
  { idd: "java", name: "Java", category: "language" },
  { idd: "c", name: "C", category: "language" },
  { idd: "cpp", name: "C++", category: "language" },
  { idd: "csharp", name: "C#", category: "language" },
  { idd: "php", name: "PHP", category: "language" },
  { idd: "go", name: "Go", category: "language" },
  { idd: "rust", name: "Rust", category: "language" },
  { idd: "swift", name: "Swift", category: "language" },
  { idd: "kotlin", name: "Kotlin", category: "language" },
  { idd: "dart", name: "Dart", category: "language" },
  { idd: "ruby", name: "Ruby", category: "language" },
  { idd: "r", name: "R", category: "language" },
  { idd: "matlab", name: "MATLAB", category: "language" },
  { idd: "bash", name: "Bash/Shell Scripting", category: "language" },
  { idd: "reactnative", name: "React Native", category: "mobile" },
  { idd: "flutter", name: "Flutter", category: "mobile" },
  { idd: "android", name: "Android (Kotlin/Java)", category: "mobile" },
  { idd: "ios", name: "iOS (Swift)", category: "mobile" },
  { idd: "expo", name: "Expo", category: "mobile" },
  { idd: "xamarin", name: "Xamarin", category: "mobile" },
  { idd: "ionic", name: "Ionic", category: "mobile" },
  { idd: "pwa_mobile", name: "Mobile PWA", category: "mobile" },
  { idd: "android_studio", name: "Android Studio", category: "mobile" },
  { idd: "ios_dev", name: "iOS Development", category: "mobile" },
  { idd: "docker", name: "Docker", category: "devops" },
  { idd: "kubernetes", name: "Kubernetes", category: "devops" },
  { idd: "ci_cd", name: "CI/CD", category: "devops" },
  { idd: "nginx", name: "Nginx", category: "devops" },
  { idd: "terraform", name: "Terraform", category: "devops" },
  { idd: "ansible", name: "Ansible", category: "devops" },
  { idd: "jenkins", name: "Jenkins", category: "devops" },
  { idd: "github_actions", name: "GitHub Actions", category: "devops" },
  { idd: "linux", name: "Linux Administration", category: "devops" },
  { idd: "prometheus", name: "Prometheus", category: "devops" },
  { idd: "grafana", name: "Grafana", category: "devops" },
  { idd: "aws", name: "AWS", category: "cloud" },
  { idd: "azure", name: "Microsoft Azure", category: "cloud" },
  { idd: "gcp", name: "Google Cloud Platform", category: "cloud" },
  { idd: "firebase", name: "Firebase", category: "cloud" },
  { idd: "vercel", name: "Vercel", category: "cloud" },
  { idd: "netlify", name: "Netlify", category: "cloud" },
  { idd: "digitalocean", name: "DigitalOcean", category: "cloud" },
  { idd: "cloudflare", name: "Cloudflare", category: "cloud" },
  { idd: "serverless", name: "Serverless Architecture", category: "cloud" },
  { idd: "aws_lambda", name: "AWS Lambda", category: "cloud" },
  { idd: "jest", name: "Jest", category: "testing" },
  { idd: "mocha", name: "Mocha", category: "testing" },
  { idd: "cypress", name: "Cypress", category: "testing" },
  { idd: "selenium", name: "Selenium", category: "testing" },
  { idd: "react_testing", name: "React Testing Library", category: "testing" },
  { idd: "unit_testing", name: "Unit Testing", category: "testing" },
  {
    idd: "integration_testing",
    name: "Integration Testing",
    category: "testing",
  },
  { idd: "e2e", name: "End-to-End Testing", category: "testing" },
  { idd: "playwright", name: "Playwright", category: "testing" },
  { idd: "vitest", name: "Vitest", category: "testing" },
  { idd: "figma", name: "Figma", category: "uiux" },
  { idd: "adobexd", name: "Adobe XD", category: "uiux" },
  { idd: "uxresearch", name: "UX Research", category: "uiux" },
  { idd: "wireframing", name: "Wireframing", category: "uiux" },
  { idd: "prototyping", name: "Prototyping", category: "uiux" },
  { idd: "usability_testing", name: "Usability Testing", category: "uiux" },
  { idd: "design_system", name: "Design Systems", category: "uiux" },
  { idd: "responsive_design", name: "Responsive Design", category: "uiux" },
  { idd: "git", name: "Git", category: "tool" },
  { idd: "github", name: "GitHub", category: "tool" },
  { idd: "gitlab", name: "GitLab", category: "tool" },
  { idd: "postman", name: "Postman", category: "tool" },
  { idd: "vscode", name: "VS Code", category: "tool" },
  { idd: "jira", name: "Jira", category: "tool" },
  { idd: "trello", name: "Trello", category: "tool" },
  { idd: "notion", name: "Notion", category: "tool" },
  { idd: "slack", name: "Slack", category: "tool" },
  { idd: "webpack_cli", name: "Webpack CLI", category: "tool" },
  { idd: "npm", name: "npm", category: "tool" },
  { idd: "yarn", name: "Yarn", category: "tool" },
  { idd: "communication", name: "Communication", category: "soft" },
  { idd: "teamwork", name: "Teamwork", category: "soft" },
  { idd: "problem_solving", name: "Problem Solving", category: "soft" },
  { idd: "time_management", name: "Time Management", category: "soft" },
  { idd: "critical_thinking", name: "Critical Thinking", category: "soft" },
  { idd: "leadership", name: "Leadership", category: "soft" },
  { idd: "adaptability", name: "Adaptability", category: "soft" },
  { idd: "creativity", name: "Creativity", category: "soft" },
  { idd: "conflict_resolution", name: "Conflict Resolution", category: "soft" },
  { idd: "public_speaking", name: "Public Speaking", category: "soft" },
  { idd: "decision_making", name: "Decision Making", category: "soft" },
];

const importData = async () => {
  try {
    // Remove duplicates by 'idd'
    const uniqueSkills = Array.from(
      new Map(skills.map((skill) => [skill.idd, skill])).values(),
    );

    await Skill.deleteMany(); // optional: clears old data
    await Skill.insertMany(uniqueSkills);

    console.log("Skills Data Inserted ✅");
    process.exit();
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
};
importData();
